language: ruby
cache: bundler
sudo: false
rvm: 
  - 2.4.0
bundler_args: --without production
jdk:
  - oraclejdk8
before_script:
  - "bin/setup"
notifications:
  email: false
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - "RAILS_VERSION=4.2.5"
services:
  - redis-server
