development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8080/fedora/rest
  base_path: <%= ENV["UMRDR_BASE_DEV"] || "/umrdr" %>
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8080/fedora/rest
  base_path: <%= ENV["UMRDR_BASE_TEST"] || "/umrdr" %>
