development:
  url: <%= ENV["UMRDR_SOLR_URL"] || "http://localhost:8080/tomcat/quod-dev/solr-hydra/umrdr" %>
test:
  url: <%= ENV["UMRDR_SOLR_URL"] || "http://localhost:8080/tomcat/quod-dev/solr-hydra/umrdr" %>

