development:
  url: <%= ENV["UMRDR_SOLR_DEV"] || "http://localhost:8080/tomcat/quod-dev/solr-hydra/umrdr" %>
test:
  url: <%= ENV["UMRDR_SOLR_TEST"] || "http://localhost:8080/tomcat/quod-dev/solr-hydra/umrdr" %>

